services:
  ecolos_sylius_eu_plugin.form.extension.type.product:
    class: Ecolos\SyliusEuPlugin\Form\Extension\ProductTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType }

  ecolos_sylius_eu_plugin.form.extension.type.product_translation:
    class: Ecolos\SyliusEuPlugin\Form\Extension\ProductTranslationTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductTranslationType, priority: -5 }

  ecolos_sylius_eu_plugin.form.extension.type.product_variant:
    class: Ecolos\SyliusEuPlugin\Form\Extension\ProductVariantTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType }

  ecolos_sylius_eu_plugin.form.extension.type.product_variant_translation:
    class: Ecolos\SyliusEuPlugin\Form\Extension\ProductVariantTranslationTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantTranslationType, priority: -5 }

  ecolos_sylius_eu_plugin.form.extension.type.taxon:
    class: Ecolos\SyliusEuPlugin\Form\Extension\TaxonTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonType }

  ecolos_sylius_eu_plugin.block_event_listener.shop.product.show.before_tabs:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@EcolosSyliusEuPlugin/productTabsContent.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.before_tabs, method: onBlockEvent }

  Ecolos\SyliusEuPlugin\Twig\HighLowVariantPricesExtension:
    tags: ['twig.extension']

  Ecolos\SyliusEuPlugin\Twig\ParseIntExtension:
    tags: ['twig.extension']

  Ecolos\SyliusEuPlugin\Twig\HasBasePriceExtension:
    tags: ['twig.extension']
