App\Entity\Product:
  fields:
    caffeine:
      type: integer
      nullable: true
    colorants:
      type: simple_array
      nullable: true
  manyToOne:
    maker:
      targetEntity: Ecolos\SyliusMakerPlugin\Entity\Maker
      joinColumn:
        name: maker_id
        nullable: true
        onDelete: "SET NULL"
        referencedColumnName: id
  repositoryClass: App\Repository\ProductRepository
  table: sylius_product
  type: entity
