App\Entity\ProductVariant:
  fields:
    caffeine:
      type: integer
      nullable: true
    colorants:
      type: simple_array
      nullable: true
  table: sylius_product_variant
  type: entity
